import type { Metadata } from 'next';
import LegalShell from '../_layout-shared';
import { SITE } from '@/lib/site';

export const metadata: Metadata = {
  title: 'Cookie policy',
  description: `Cookies used by ${SITE.name} and how to manage consent.`,
  alternates: { canonical: `${SITE.url}/cookie-policy` },
  robots: { index: true, follow: true },
};

// REPLACE: paste real cookie policy from CookieYes/Termly here.
export default function CookiePolicyPage() {
  return (
    <LegalShell eyebrow="Legal · Cookies" title="Cookie policy" updatedAt="29 April 2026">
      <p>
        <strong>This is a placeholder.</strong> Replace with the cookie policy
        generated by your CookieYes scan. Keep the surrounding shell — swap the
        body copy.
      </p>

      <h2>What cookies we set</h2>
      <ul>
        <li>
          <strong>Strictly necessary</strong> — session, CSRF, consent state.
          Cannot be opted out.
        </li>
        <li>
          <strong>Analytics</strong> — Google Analytics 4 (via GTM). Used to
          measure traffic. Consent-gated.
        </li>
        <li>
          <strong>Advertising</strong> — Meta Pixel, LinkedIn Insight (via
          GTM). Used for retargeting. Consent-gated.
        </li>
      </ul>

      <h2>Manage preferences</h2>
      <p>
        The CookieYes banner appears on first visit; click <em>Manage</em> at
        any time via the floating consent widget to update your choices.
      </p>

      <h2>Contact</h2>
      <p>
        Questions? <a href="mailto:hello@manhaj.ai">hello@manhaj.ai</a>
      </p>
    </LegalShell>
  );
}
