export const SITE = {
  name: 'MANHAJ',
  domain: 'manhaj.ahmadbukhari.com',
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://manhaj.ahmadbukhari.com',
  tagline: 'The AI Operating System architected uniquely for your business.',
  positioning:
    "Built on a defined 6-layer revenue foundation. Configured to how you actually run. Owned by you.",
  motto: "Your OS is no one else's.",
  founder: 'Ahmad Bukhari',
  email: 'ahmadbukhari4245@gmail.com',
  bookingUrl: 'https://cal.com/ahmad-bukhari/ai-consultancy-call-with-ab',
  bookingSlug: 'ahmad-bukhari/ai-consultancy-call-with-ab',
  founderUrl: 'https://ahmadbukhari.com/about',
  companyName: 'Aixcel Solutions',
  companyUrl: 'https://aixcelsolutions.com',
  githubUrl: 'https://github.com/syedahmad0786',
  linkedinUrl: 'https://www.linkedin.com/in/bukhariahmad',
  socialImage: '/opengraph-image',
  contentUpdatedAt: '2026-07-22',
} as const;
